Sarthak Dandotiya **17BCE0203**

## Assesment 3

### Question 1
Write a program to show the implementation of Elias Delta and Golomb Encoding-decoding (both for m = 2N and M ≠ 2N) techniques.
(x=37, b=11, b=8)

In [39]:
from math import log, ceil, floor


def log2(x): return log(x, 2)


def binary(x, l=1):
    fmt = '{0:0%db}' % l
    return fmt.format(x)


def unary(x):
    return x*'1'+'0'


def elias_generic(lencoding, x):
    if x == 0:
        return '0'
    l = 1+int(log2(x))
    a = x - 2**(int(log2(x)))
    k = int(log2(x))
    return lencoding(l) + binary(a, k)


def golomb(b, x):
    q = int((x) / b)
    r = int((x) % b)
    l = int(ceil(log2(b)))
#     print ("Golomb",q,r,l)
    return unary(q) + binary(r, l)


def elias_gamma(x):
    return elias_generic(unary, x)


def elias_delta(x):
    return elias_generic(elias_gamma, x)


print("10 returns(with base 2) %5d: %-10s : %-10s : %-10s" %
      (10, elias_gamma(10), elias_delta(10), golomb(10, 2)))

print("37 is golomb encoded as => ", golomb(37,11))

def elias_delta_decoding(strings):
    j = 0
    for i in strings:
        if i == '1':
            break
        j = j + 1
    strings = strings[2*j+1:]
    strings = '1' + strings
    number = int(strings, 2)
    return number


decode = (input("Enter the value which has to be decoded: "))
b = int(input("Enter the value of b: "))

i = floor(log(b, 2))
d = 2**(i+1) - b
print("The decoded golomb numbers : ")


def decoder(decodes):
    q_length = 0
    for k in decodes:
        q_length = q_length + 1
        if(k == '1'):
            break
    q = q_length - 1
    r = int(decodes[q_length:q_length+i], 2)
    val = q_length+i
    if (r >= d):
        r = int(decodes[q_length:q_length+i+1], 2) - d
    val = val + 1
    print(b*q + r + 1)
    if(len(decodes) > val):
        decoder(decodes[val:])

decoder(decode)

10 returns(with base 2)    10: 11110010   : 111000010  : 00010     
37 is golomb encoded as =>  0001011
Enter the value which has to be decoded: 0001011
Enter the value of b: 11
The decoded golomb numbers : 
37


<hr>
<hr>

### Question 2
Write a program to display the page rank of the given directed graph representing
web of six pages and damping factor is 0.9. Input to the program must be adjacency
matrix or adjacency list of the given web graph along with damping factor and
threshold value (stopping criteria:- ε = 0.05). The program must print the result after
each of the following scenario:
<br>
<ul>
    <li>Handling the nodes with no outgoing links</li>
    <li>Stochastic matrix formation</li>
    <li>Page rank of all the six nodes after each iteration</li>
    <li>Total number iteration count until stopping criteria</li>
</ul>

<img src="L2Q2.png" style="width: 35%">

In [2]:
import numpy as np
d = 0.8 #damping factor
adj = np.array([[0,1/2,1/2,0,0,0],[1/4,0,0,1/4,1/4,1/4],[1/2,0,0,0,0,1/2],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,1,0]])
print("Adjacency Matrix: \n", adj, "\n\n")

n=len(adj)
for i in range(n):
    if any(adj[i])==0:
        for l in range(n):
            adj[i][l]=1/n
print("Stochastic Matrix:\n", adj, "\n\n")

E = np.ones((n,n))
sto=(1-d)*E/n+d*np.transpose(adj)
# print("Stochastic Matrix: \n",sto, "\n\n")


def pagerank(P,r):
        pagerank.count=getattr(pagerank,"count",1)
        Pk=np.dot(r,P)
        print("Page rank after Iteration ",pagerank.count,": ",Pk,"\n")
        print("--------------------------------------------------------------------------------------------------------------\n")
        temp=0
        for i in range(len(Pk)):
                if(abs(Pk[i]-P[i])<0.05):
                        temp=temp+1
        if(temp<len(Pk)):
                pagerank.count+=1
                pagerank(Pk,r)
        else:
                lst=[]
                for i in Pk:
                        lst.append(i)
                lst.sort(reverse=True)
                rank=[]
                for i in lst:
                        t=np.where(Pk==i)
                        rank.append(t)
                print("Total number of Iterations are: ",pagerank.count,"\n\n")
                print("Ranks are: \n")
                for i in range(len(rank)):
                                    print(rank[i][0][0]+1,end=' ')
                print("\n")

initial_pr=(np.ones(6,dtype=float)/6)

r1=((1-d)*E)/6
r2=d*sto
r=r1+r2
print("--------------------------------------------------------------------------------------------------------------\n")
pagerank(initial_pr, r)

Adjacency Matrix: 
 [[0.   0.5  0.5  0.   0.   0.  ]
 [0.25 0.   0.   0.25 0.25 0.25]
 [0.5  0.   0.   0.   0.   0.5 ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   1.   0.  ]] 


Stochastic Matrix:
 [[0.         0.5        0.5        0.         0.         0.        ]
 [0.25       0.         0.         0.25       0.25       0.25      ]
 [0.5        0.         0.         0.         0.         0.5       ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         1.         0.        ]] 


--------------------------------------------------------------------------------------------------------------

Page rank after Iteration  1 :  [0.17555556 0.14888889 0.14888889 0.12222222 0.22888889 0.17555556] 

--------------------------------------------------------------------------------------------------------------

Page rank afte

<hr>
<hr>

### Question 3
Write a program to implement HITS algorithm for the graph shown in Question No. 2
and display the final authority score and hub score of all the nodes after stopping
criteria is attained.

In [41]:
import numpy as np
import math

def hits(A,H,L,Lt):
    hits.count=getattr(hits,"count",1)
    Ak=np.dot(np.dot(Lt,L),A)
    Hk=np.dot(np.dot(L,Lt),H)
    As=[]
    for i in Ak:
        As.append(i**2)
    Ak=Ak/float(math.sqrt(sum(As)))

    Hs=[]
    for i in Hk:
        Hs.append(i**2)
    Hk=Hk/float(math.sqrt(sum(Hs)))

    print("Authority Score in Iteration ",hits.count,":\n",Ak,"\n")
    print("Hub Score in Iteration ",hits.count,":\n",Hk,"\n")
    print("---------------------------------------------------------------------------\n")
    
    temp=0
    for i in range(len(Ak)):
        if(abs(Ak[i]-A[i])<0.05 and abs(Hk[i]-H[i])<0.05):
            temp=temp+1
    if(temp<len(Ak)):
        hits.count+=1
        hits(Ak,Hk,L,Lt)
    else:
        print("Total number of Iterations are: ",hits.count)
        print("\nAuthority and Hub score in last iteration are the final scores")
        

L=np.array([[0,1,1,0,0,0],
                    [0,0,0,0,0,0],
                    [1,1,0,0,1,0],
                    [0,0,0,0,1,1],
                    [0,0,0,1,0,1],
                    [0,0,0,1,0,0]])

print("Adjency Matrix L: \n\n",L,"\n\n")

Lt=L.transpose()

Ain=np.ones(6)
Hin=np.ones(6)

print("---------------------------------------------------------------------------\n")
hits(Ain,Hin,L,Lt)


Adjency Matrix L: 

 [[0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 1 0 0]] 


---------------------------------------------------------------------------

Authority Score in Iteration  1 :
 [0.31980107 0.53300179 0.21320072 0.31980107 0.53300179 0.42640143] 

Hub Score in Iteration  1 :
 [0.35856858 0.         0.5976143  0.47809144 0.47809144 0.23904572] 

---------------------------------------------------------------------------

Authority Score in Iteration  2 :
 [0.34045882 0.5237828  0.18332398 0.2618914  0.57616108 0.41902624] 

Hub Score in Iteration  2 :
 [0.32781098 0.         0.65562195 0.50661696 0.41721397 0.17880599] 

---------------------------------------------------------------------------

Authority Score in Iteration  3 :
 [0.35124594 0.52367576 0.17242982 0.22990643 0.59392495 0.40872255] 

Hub Score in Iteration  3 :
 [0.3219924  0.         0.68789287 0.51226064 0.37321847 0.14636018] 

------------------------------------------

<hr>
<hr>